version: "3.8"
services:
  web:
    container_name: cts-staging
    build:
      context: /home/ubuntu/cashtokens-studio/staging
      dockerfile: ./deployment/staging.Dockerfile
    ports:
      - "3001:3001"


